nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: "${GITHUB_NPM_REGISTRY_TOKEN}"

npmScopes:
  thepolicylab-projectportals:
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
